[server]
# show percentage on the right of the OSD
show_percentage = true

# OSD display duration in milliseconds (200-60000)
duration = 1000

# The maximum volume that can be reached in %
# max_volume = 150

## The minimum brightness that can be reached in %
min_brightness = 5
