[gui]
absolute_position=
always_on_top=true
background_color=#181818
bounce=true
bounce_duration=500
font=IosevkaTerm Nerd Font
font_size=20
font_variant=medium
foreground_color=#c4c3c1
height=24
in_animation=38
in_animation_duration=800
max_length=-1
offset_x=0
offset_y=0
opacity=100
out_animation=13
out_animation_duration=800
position=top_right
screen=

[icons]
critical_icon=
info_icon=
warning_icon=

[main]
activate_command=
duration=4000
host=127.0.0.1
port=9797
sound_command=
