# --- Gruber-Darker-Ayu Appearance ---

# Window colors
# border background text indicator child_border
client.focused          #363652 #363652 #E6B450 #E6B450 #363652
client.focused_inactive #2a2a3e #2a2a3e #6B7B8E #6B7B8E #2a2a3e
client.unfocused        #1c1c2a #1c1c2a #3d4658 #3d4658 #1c1c2a
client.urgent           #FF7B85 #FF7B85 #ffffff #FF7B85 #FF7B85
client.placeholder      #181818 #181818 #ffffff #181818 #181818
client.background       #181818
