# --- Autostart ---

exec --no-startup-id ~/.fehbg
exec --no-startup-id dex --autostart --environment i3
exec --no-startup-id greenclip daemon
exec --no-startup-id QT_STYLE_OVERRIDE=Fusion flameshot &
exec --no-startup-id twmnd
exec --no-startup-id xss-lock --transfer-sleep-lock -- ~/.config/i3/scripts/lock.sh --nofork
exec --no-startup-id nm-applet
exec --no-startup-id xset -b
# exec --no-startup-id picom &
exec --no-startup-id emacs
