#!/bin/bash

pactl set-source-mute @DEFAULT_SOURCE@ toggle

if [[ $(pactl get-source-mute @DEFAULT_SOURCE@) == *"yes"* ]]; then
    notify-send -t 700 "Input Muted"
else
    notify-send -t 700 "Input Unmuted"
fi
