#!/bin/bash

# CACHE FILE
LAST_WALLPAPER_CACHE="$HOME/.cache/last_wallpaper.path"

# Kill any existing swaybg instances
pkill -x swaybg

# Restore last wallpaper if cache file exists
if [ -f "$LAST_WALLPAPER_CACHE" ]; then
    WALLPAPER_PATH=$(cat "$LAST_WALLPAPER_CACHE")
    if [ -n "$WALLPAPER_PATH" ]; then
        ~/.config/hypr/scripts/set_wallpaper "$WALLPAPER_PATH"
        
        swaync-client --reload 2>/dev/null || true
    fi
fi

