#!/bin/bash
STATE="/tmp/noctalia_bar_float"

noctalia msg bar-reserve-toggle

if [ -f "$STATE" ]; then
    rm -f "$STATE"
    notify-send -t 1000 "Noctalia" "Bar docked"
else
    touch "$STATE"
    notify-send -t 1000 "Noctalia" "Bar floating"
fi
