#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    repeat_rate = 60
    repeat_delay = 300

    sensitivity = 1.0 # -1.0 - 1.0, 0 means no modification.

    # touchpad {
    #     natural_scroll = true
    # }
}

plugin {
    scrolloverview {
        columns = 3              # number of columns in the overview grid
        gap = 10                 # gap between workspace cards
        overview_center = 1      # center the overview (0 or 1)
    }
}

# See https://wiki.hypr.land/Configuring/Gestures

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = 1.0
}
