#################
### AUTOSTART ###
#################

exec-once = fcitx5 -d
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = swaync
exec-once = ~/.config/hypr/scripts/restore_wallpaper
# exec-once = wal -R
exec-once = sleep 0.5 && waybar
exec-once = walker --gapplication-service
exec-once = elephant
exec-once = ~/.config/hypr/scripts/xdg_launch
exec-once = ~/.config/hypr/scripts/run_hypridle
exec-once = swayosd-server
exec-once = emacs
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = ~/.config/hypr/scripts/break
exec-once = hyprctl keyword device[synps/2-synaptics-touchpad]:enabled false
exec-once = wl-gammarelay-rs run
exec-once = ~/.config/hypr/scripts/hotcorner
#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = XMODIFIERS,@im=fcitx
env = QT_IM_MODULE,fcitx
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
# On Wayland, GTK_IM_MODULE should not be set (Wayland input method protocol is used instead)
