#################
### AUTOSTART ###
#################

exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = wl-paste --watch clipman store
exec-once = swaync &
exec-once = ~/.config/hypr/scripts/restore_wallpaper.sh
exec-once = wal -R
exec-once = walker --gapplication-service
exec-once = elephant
exec-once = ~/.config/hypr/scripts/xdg_launch.sh
exec-once = ~/.config/hypr/scripts/run_hypridle.sh
exec-once = swayosd-server
exec-once = emacs
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
