hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XMODIFIERS", "@im=fcitx")
hl.env("QT_IM_MODULE", "fcitx")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.on("hyprland.start", function()
    hl.exec_cmd("fcitx5 -d")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("swaync")
    hl.exec_cmd("~/.config/hypr/scripts/restore_wallpaper")
    hl.exec_cmd("sleep 0.5 && waybar")
    hl.exec_cmd("walker --gapplication-service")
    hl.exec_cmd("elephant")
    hl.exec_cmd("~/.config/hypr/scripts/xdg_launch")
    hl.exec_cmd("~/.config/hypr/scripts/run_hypridle")
    hl.exec_cmd("swayosd-server")
    hl.exec_cmd("emacs")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("~/.config/hypr/scripts/break")
    hl.exec_cmd("wl-gammarelay-rs run")
    hl.exec_cmd("~/.config/hypr/scripts/hotcorner")
end)
