#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hypr.land/Configuring/Variables/

# https://wiki.hypr.land/Configuring/Variables/#general
general {
    gaps_in  = 5
    gaps_out = 10

    border_size = 0

    col.active_border = rgb(E6B450) rgb(6DCFFF) rgb(6DCFFF) rgb(E6B450) 45deg
    col.inactive_border = rgb(1c1c2a) rgb(1c1c2a) rgb(1c1c2a) rgb(1c1c2a) 45deg
    resize_on_border = true

    allow_tearing = true

    layout = master
}

# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 0


    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 0.79


    shadow {
        enabled = false
        range = 4
        render_power = 5
        color = rgba(0d0d0dee)
    }

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = false
        size = 4
        passes = 2

        vibrancy = 0.1696
    }
}

# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
# dwindle {
#     pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
#     preserve_split = true # You probably want this
# }

group {
    groupbar {
        height = 15
        # gradients = true
        render_titles = false
        rounding = 0
        col.active = rgb(E6B450)
        col.inactive = rgba(282828EE)
    }
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    orientation = left
    mfact = 0.5
    new_on_top = false
    new_status = slave
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
  #  vfr = true
    vrr = 0
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    disable_splash_rendering = true
}

render {
    direct_scanout = true
}

xwayland {
    force_zero_scaling = true
}

debug {
    disable_logs = true
}

render {
    direct_scanout = false
}

misc {
    vrr = 2
}