###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$audiosettings = pavucontrol
$codeditor = emacs
$fileManager = dolphin
$discord = vesktop-wayland
$menu=rofi -show drun -config ~/.config/rofi/drun.rasi
$tmenu = tofi-drun -c ~/.config/tofi/configA --drun-launch=true
$wallpaper_selector = ~/.config/hypr/scripts/wallpaper_select.sh
$wallpaper_changer = ~/.config/hypr/scripts/wallpaper_changer.sh
$wallpaper_changer-h = ~/.config/hypr/scripts/wallpaper_changer_h.sh
$wallpaper_changer-cg = ~/.config/hypr/scripts/wallpaper_changer_cg.sh
$camera = cheese
$toggle_microphone=pactl set-source-mute @DEFAULT_SOURCE@ toggle
$colorPicker=hyprpicker
$fsc=nbfc set -s 100 || nbfc set -a
