###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$audiosettings = pavucontrol
$codeditor = emacs
$fileManager = nautilus
$menu=rofi -show drun -config ~/.config/rofi/drun.rasi
$tmenu = tofi-drun -c ~/.config/tofi/configA --drun-launch=true
$wallpaper_selector = ~/.config/hypr/scripts/wallpaper_select
$camera = cheese
$look-menu = lookapp
$discord = brave-origin --profile-directory=Default --app=https://discord.com/channels/@me
$telegram = brave-origin --profile-directory=Default --app=https://web.telegram.org
$facebook = brave-origin --profile-directory=Default --app=https://facebook.com
$toggle_microphone=pactl set-source-mute @DEFAULT_SOURCE@ toggle
$colorPicker=hyprpicker
$fsc=nbfc set -s 100 || nbfc set -a
