###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = st
$herdr = st herdr
$audiosettings = pavucontrol
$codeditor = emacs
$fileManager = nautilus
$menu=rofi -show drun -config ~/.config/rofi/drun.rasi
$tmenu = tofi-drun -c ~/.config/tofi/configA --drun-launch=true
$wallpaper_selector = noctalia msg panel-toggle wallpaper
$camera = cheese
$look-menu = lookapp
$discord-web = brave-origin --profile-directory=Default --app=https://discord.com/channels/@me
$discord = discord
$telegram = Telegram
$reddit   = brave-origin --profile-directory=Default --app=https://reddit.com
$facebook = brave-origin --profile-directory=Default --app=https://facebook.com
$facebook2 = brave-origin --profile-directory=Profile\ 1/ --app=https://facebook.com
$whatsapp = brave-origin --profile-directory=Default --app=https://web.whatsapp.com
$yt = brave-origin --profile-directory=Default --app=https://youtube.com
$twitch = brave-origin --profile-directory=Default --app=https://www.twitch.tv/
$toggle_microphone=pactl set-source-mute @DEFAULT_SOURCE@ toggle
$colorPicker=hyprpicker
$fsc=nbfc set -s 100 || nbfc set -a
$setup-workspace=~/.config/hypr/scripts/workspace-setup

$default_wall=noctalia msg wallpaper-set ~/Pictures/wall.jpg

# Animation toggle (true/false) - set to false to disable all animations for max performance
$enable_animations = true
