windowrule {
  name = move-kitty
  match:class = kitty
  float = true
  size = 1090 850
}

windowrule {
  name = move-peaclock
  match:class = peaclock
  move = 100 100
  float = true
  size = 100, 200
}

windowrule {
  name = move-emacs
  match:class = Emacs
}

windowrule {
  name = Dolphin
  match:class = org.kde.dolphin
  float = true
  size = 1500 900
}

windowrule {
  name = move-xdg-desktop-portal-gtk
  match:class = xdg-desktop-portal-gtk
  float = true
  size = 1020 700
}

windowrule {
  name = move-org.pulseaudio.pavucontrol
  match:class = org.pulseaudio.pavucontrol
  float = true
  size = 1020 700
}

windowrule {
  name = move-cg-timer
  match:class = cg-timer
  move = 900 10
  float = true
  size = 1000 250
}

windowrule {
  name = move-org.gnome.Loupe
  match:class = org.gnome.Loupe
  float = true
  size = 1090 850
}

windowrule {
  name = waypaper
  match:class = waypaper
  float = true
  size = 1090 850
}
