# language-specific settings

[[language]]
name = "c"
file-types = ["c"]
scope = "source.c"
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "cpp"
file-types = ["cpp", "cc", "cxx"]
scope = "source.cpp"
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "typst"
file-types = ["typ"]
scope = "source.typ"
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "rust"
file-types = ["rs"]
scope = "source.rust"
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "bash"
file-types = ["sh"]
scope = "source.sh"
indent = { tab-width = 4, unit = "    " }
auto-format = true

# [[language]]
# name = "asm"
# scope = "source.asm"
# file-types = ["asm", "s", "S"]  # common assembly file extensions
# language-servers = ["asm-lsp"]

# [language-server.asm-lsp]
# command = "asm-lsp"
# args = ["--stdio"]

[[language]]
name = "javascript"
file-types = ["js", "jsx", "ts", "tsx"]
scope = "source.js"
indent = { tab-width = 4, unit = "  " }
auto-format = true

# HTML
[[language]]
name = "html"
file-types = ["html", "htm"]
language-servers = ["vscode-html"]

[language-server.vscode-html]
command = "vscode-html-language-server"
args = ["--stdio"]

# Hyprland Config
[[language]]
name = "hyprlang"
file-types = ["conf"]
scope = "source.conf"
language-servers = ["hyprls"]

[language-server.hyprls]
command = "hyprls"

# TypeScript
[[language]]
name = "typescript"
file-types = ["ts"]
scope = "source.ts"
language-servers = ["ts-lsp"]

# JSON (comes with vscode-langservers-extracted)
[[language]]
name = "json"
file-types = ["json"]
scope = "source.json"
language-servers = ["vscode-json"]

[language-server.vscode-json]
command = "vscode-json-language-server"
args = ["--stdio"]

# CSS
[[language]]
name = "css"
file-types = ["css"]
scope = "source.css"
language-servers = ["vscode-css"]

[language-server.vscode-css]
command = "vscode-css-language-server"
args = ["--stdio"]

# Fish Shell
[[language]]
name = "fish"
file-types = ["fish"]
scope = "source.fish"
language-servers = ["fish-lsp"]

[language-server.fish-lsp]
command = "fish-lsp"

# Common Lisp
[[language]]
name = "lisp"
file-types = ["lisp"]
scope = "source.lisp"
language-servers = ["cl-lsp"]

[language-server.cl-lsp]
command = "cl-lsp"

# Dart
[[language]]
name = "dart"
file-types = ["dart"]
scope = "source.dart"
language-servers = ["dart"]

[language-server.dart]
command = "dart"

# Dockerfile
[[language]]
name = "dockerfile"
file-types = ["docker"]
scope = "docker"
language-servers = ["dockerfile-ls"]

[language-server.dockerfile-ls]
command = "dockerfile-language-server"
args = ["--stdio"]



# Elixir
[[language]]
name = "elixir"
file-types = ["ex", "exs"]
scope = "source.ex"
language-servers = ["elixir-ls"]

[language-server.elixir-ls]
command = "elixir-ls"



# Go
[[language]]
name = "go"
file-types = ["go"]
scope = "source.go"
language-servers = ["gopls"]

[language-server.gopls]
command = "gopls"

# Lua
[[language]]
name = "lua"
file-types = ["lua"]
scope = "source.lua"
language-servers = ["lua-ls"]

[language-server.lua-ls]
command = "lua-language-server"

[[language]]
name = "ada"
scope = "source.ada"
file-types = ["adb", "ads", "gpr"]
language-servers = ["ada-ls"]

[language-server.ada-ls]
command = "ada_language_server"
args = ["--stdio"]

